name: Build & Pack Capacitor Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual execution
  release:
    types: [created] # Runs when a new GitHub Release is created

jobs:
  build:
    name: Build and Pack Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Build Plugin
        run: npm run build

      - name: Pack NPM Package
        run: npm run pack

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capacitor-nodejs-package
          path: "*.tgz"

  release:
    name: Upload to GitHub Releases
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Download Built Package
        uses: actions/download-artifact@v4
        with:
          name: capacitor-nodejs-package

      - name: Upload Package to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tgz"
