release:
  name: Upload to GitHub Releases
  needs: build
  runs-on: ubuntu-latest
  if: github.event_name == 'release'

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  

    - name: Download Built Package
      uses: actions/download-artifact@v4
      with:
        name: capacitor-nodejs
        path: .

    - name: Upload Package to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: "./capacitor-nodejs-*.tgz"  
